
--DROP OLD OBJECTS

-- Permite que no reviente si las tablas no existen
WHENEVER SQLERROR CONTINUE
DROP TABLE FACTURA CASCADE CONSTRAINTS PURGE;
DROP TABLE PRODUCTO CASCADE CONSTRAINTS PURGE;
DROP TABLE CLIENTE  CASCADE CONSTRAINTS PURGE;
DROP TABLE FORMA_PAGO CASCADE CONSTRAINTS PURGE;

-- Volver a modo estricto
WHENEVER SQLERROR EXIT SQL.SQLCODE


--CREATE TABLES

-- FORMA_PAGO
CREATE TABLE FORMA_PAGO (
  CODIGO      NUMBER(2)    CONSTRAINT PK_FORMA_PAGO PRIMARY KEY,
  DESCRIPCION VARCHAR2(30) NOT NULL
);

-- CLIENTE
CREATE TABLE CLIENTE (
  ID_CLIENTE NUMBER(10)    CONSTRAINT PK_CLIENTE PRIMARY KEY,
  NOMBRE     VARCHAR2(100) NOT NULL,
  RUT        VARCHAR2(20)  NOT NULL UNIQUE,
  TELEFONO   VARCHAR2(30),
  COMUNA     VARCHAR2(60),
  CORREO     VARCHAR2(120),
  ESTADO     CHAR(1)       DEFAULT 'A' NOT NULL,  -- A=activo, I=inactivo
  CREDITO    NUMBER(12,2)  DEFAULT 0,
  SALDO      NUMBER(12,2)  DEFAULT 0,
  CONSTRAINT CK_CLIENTE_ESTADO   CHECK (ESTADO IN ('A','I')),
  CONSTRAINT CK_CLIENTE_VALORES  CHECK (CREDITO >= 0 AND SALDO >= 0)
);

-- PRODUCTO
CREATE TABLE PRODUCTO (
  ID_PRODUCTO       NUMBER(10)    CONSTRAINT PK_PRODUCTO PRIMARY KEY,
  DESCRIPCION       VARCHAR2(200) NOT NULL,
  PROCEDENCIA       CHAR(1)       NOT NULL, -- 'i' importado, 'n' nacional
  VALOR_COMPRA_USD  NUMBER(12,2),           -- puede ser NULL (sin registro)
  VALOR_UNITARIO    NUMBER(12,2)  NOT NULL,
  TOTALSTOCK        NUMBER(10),
  CONSTRAINT CK_PRODUCTO_PROC    CHECK (LOWER(PROCEDENCIA) IN ('i','n')),
  CONSTRAINT CK_PRODUCTO_VALOR   CHECK (VALOR_UNITARIO >= 0)
);

-- FACTURA
CREATE TABLE FACTURA (
  NUMERO_FACTURA NUMBER(12)  CONSTRAINT PK_FACTURA PRIMARY KEY,
  FECHA_FACTURA  DATE        NOT NULL,
  RUT_CLIENTE    VARCHAR2(20) NOT NULL,
  MONTO_NETO     NUMBER(12,2) NOT NULL,
  CODIGO_PAGO    NUMBER(2)     NOT NULL,
  CONSTRAINT FK_FACTURA_FORMA_PAGO FOREIGN KEY (CODIGO_PAGO)
    REFERENCES FORMA_PAGO(CODIGO),
  CONSTRAINT FK_FACTURA_CLIENTE_RUT FOREIGN KEY (RUT_CLIENTE)
    REFERENCES CLIENTE(RUT)
);

-- Formas de pago
INSERT INTO FORMA_PAGO VALUES (1,'EFECTIVO');
INSERT INTO FORMA_PAGO VALUES (2,'TARJETA DEBITO');
INSERT INTO FORMA_PAGO VALUES (3,'TARJETA CREDITO');
INSERT INTO FORMA_PAGO VALUES (4,'CHEQUE');

-- Clientes
INSERT INTO CLIENTE VALUES (1,'Ana Morales','12.345.678-5','9 1234 5678','Maipú','ana.morales@gmail.com','A',500000,120000);
INSERT INTO CLIENTE VALUES (2,'Bruno Cárdenas','13.987.654-K',NULL,NULL,'bruno@empresa.cl','A',300000,260000);
INSERT INTO CLIENTE VALUES (3,'Carla Pérez','15.111.222-3','2 2345 6789','Providencia',NULL,'A',800000,710000);
INSERT INTO CLIENTE VALUES (4,'Diego Fuentes','16.222.333-4',NULL,'Ñuñoa','diego.f@gmail.com','I',100000,10000);
INSERT INTO CLIENTE VALUES (5,'Elena Contreras','17.333.444-5','2 8765 4321','Las Condes','elena@yahoo.com','A',900000,300000);
INSERT INTO CLIENTE VALUES (6,'Felipe Rojas','18.444.555-6',NULL,'La Florida','felipe.rojas@outlook.com','A',200000,90000);
INSERT INTO CLIENTE VALUES (7,'Gabriela Martínez','19.555.666-7','9 5555 6666',NULL,'gmartinez@duocuc.cl','A',1000000,200000);
INSERT INTO CLIENTE VALUES (8,'Hugo Silva','20.666.777-8','2 7654 3210','Puente Alto','hugo.silva@empresa.cl','A',400000,360000);
INSERT INTO CLIENTE VALUES (9,'Isidora córtez','21.777.888-9',NULL,'Santiago','isidora@mail.com','A',250000,90000);
INSERT INTO CLIENTE VALUES (10,'Javier Ortiz','22.888.999-K',NULL,NULL,NULL,'A',150000,135000);

-- Productos
INSERT INTO PRODUCTO VALUES (1001,'Zapato formal hombre cuero negro','i',40,69990,120);
INSERT INTO PRODUCTO VALUES (1002,'Zapato deportivo running mujer','i',30,54990,35);
INSERT INTO PRODUCTO VALUES (1003,'Zapato casual unisex gamuza','n',20,39990,85);
INSERT INTO PRODUCTO VALUES (1004,'Zapato trekking impermeable','i',55,84990,58);
INSERT INTO PRODUCTO VALUES (1005,'Zapato escolar cuero','i',NULL,25990,0);
INSERT INTO PRODUCTO VALUES (1006,'Plantilla anatómica (no zapato)','i',3,6990,500);
INSERT INTO PRODUCTO VALUES (1007,'Zapato bota mujer taco alto','i',48,79990,42);
INSERT INTO PRODUCTO VALUES (1008,'Zapato mocasín hombre','n',18,45990,78);
INSERT INTO PRODUCTO VALUES (1009,'Zapato sandalia mujer','i',12,29990,15);
INSERT INTO PRODUCTO VALUES (1010,'Zapato cuero premium','i',65,109990,82);

-- Facturas (año anterior al actual para que Caso 1 funcione siempre)
INSERT INTO FACTURA VALUES (50001, DATE '2024-01-15','12.345.678-5', 45000,1);
INSERT INTO FACTURA VALUES (50002, DATE '2024-03-10','13.987.654-K', 85000,2);
INSERT INTO FACTURA VALUES (50003, DATE '2024-06-21','15.111.222-3',120000,3);
INSERT INTO FACTURA VALUES (50004, DATE '2024-09-05','17.333.444-5',200000,4);
INSERT INTO FACTURA VALUES (50005, DATE '2024-12-28','21.777.888-9', 99999,3);
-- otros años para validar filtro
INSERT INTO FACTURA VALUES (49990, DATE '2023-11-20','20.666.777-8',130000,1);
INSERT INTO FACTURA VALUES (51000, DATE '2025-02-14','12.345.678-5', 60000,2);

COMMIT;

--INDEX SUGGESTIONS

CREATE INDEX IX_FACTURA_FECHA  ON FACTURA (FECHA_FACTURA);
CREATE INDEX IX_FACTURA_MONTO  ON FACTURA (MONTO_NETO);
CREATE INDEX IX_CLIENTE_NOMBRE ON CLIENTE (NOMBRE);

--REPORT: CASO 1

SELECT
  f.NUMERO_FACTURA                                        AS "N° FACTURA",
  TO_CHAR(f.FECHA_FACTURA,'YYYY-MM-DD')                   AS "FECHA",
  LPAD(REGEXP_REPLACE(f.RUT_CLIENTE,'[^0-9kK]'),10,'0')   AS "RUT CLIENTE",
  CASE
    WHEN f.MONTO_NETO BETWEEN 0 AND 50000      THEN 'Bajo'
    WHEN f.MONTO_NETO BETWEEN 50001 AND 100000 THEN 'Medio'
    ELSE 'Alto'
  END                                                     AS "CLASIF. MONTO",
  CASE f.CODIGO_PAGO
    WHEN 1 THEN 'EFECTIVO'
    WHEN 2 THEN 'TARJETA DEBITO'
    WHEN 3 THEN 'TARJETA CREDITO'
    ELSE 'CHEQUE'
  END                                                     AS "FORMA PAGO",
  TO_CHAR(f.MONTO_NETO,'999G999G999D00')                  AS "MONTO NETO"
FROM FACTURA f
WHERE EXTRACT(YEAR FROM f.FECHA_FACTURA) = EXTRACT(YEAR FROM SYSDATE) - 1
ORDER BY f.FECHA_FACTURA DESC, f.MONTO_NETO DESC;

--REPORT: CASO 2

SELECT
  c.ID_CLIENTE                              AS "ID",
  c.NOMBRE                                  AS "NOMBRE",
  RPAD(REVERSE(REGEXP_REPLACE(c.RUT,'[^0-9kK]','')),12,'*')
                                            AS "RUT INVERSO",
  NVL(c.TELEFONO,'Sin teléfono')            AS "TELEFONO",
  NVL(c.COMUNA,'Sin comuna')                AS "COMUNA",
  NVL(c.CORREO,'Correo no registrado')      AS "CORREO",
  CASE WHEN c.CORREO IS NULL
       THEN 'N/A'
       ELSE LOWER(SUBSTR(c.CORREO,INSTR(c.CORREO,'@')+1))
  END                                       AS "DOMINIO",
  TO_CHAR(c.CREDITO,'999G999G999D00')       AS "CREDITO",
  TO_CHAR(c.SALDO,'999G999G999D00')         AS "SALDO",
  CASE WHEN c.CREDITO>0
       THEN ROUND((c.SALDO/c.CREDITO)*100,2)
       ELSE NULL END                        AS "USO_%",
  CASE
    WHEN c.CREDITO = 0 OR c.CREDITO IS NULL THEN 'SIN CREDITO'
    WHEN (c.SALDO/c.CREDITO) < 0.5          THEN 'Bueno'
    WHEN (c.SALDO/c.CREDITO) <= 0.8         THEN 'Regular'
    ELSE 'Crítico'
  END                                       AS "CATEGORIA",
  CASE
    WHEN c.CREDITO = 0 OR c.CREDITO IS NULL THEN 'Sin crédito disponible'
    WHEN (c.SALDO/c.CREDITO) < 0.5
      THEN 'Disponible: ' || TO_CHAR(c.CREDITO - c.SALDO,'999G999G999D00')
    WHEN (c.SALDO/c.CREDITO) <= 0.8
      THEN 'Saldo actual: ' || TO_CHAR(c.SALDO,'999G999G999D00')
    ELSE 'Crédito crítico (>80%)'
  END                                       AS "MENSAJE"
FROM CLIENTE c
WHERE c.ESTADO = 'A'
  AND NVL(c.CREDITO,0) > 0
ORDER BY c.NOMBRE ASC;

--REPORT: CASO 3

SET ECHO OFF
SET VERIFY OFF
SET HEADING ON
SET TERMOUT ON
SET TAB OFF
SET TRIMSPOOL ON
SET LINESIZE 220
SET PAGESIZE 200
ALTER SESSION SET NLS_NUMERIC_CHARACTERS='.,';


COLUMN "ID PRODUCTO"         HEADING "ID PRODUCTO"         FORMAT 999999
COLUMN "DESCRIPCION"         HEADING "DESCRIPCION"         FORMAT A45
COLUMN "ORIGEN"              HEADING "ORIGEN"              FORMAT A6
COLUMN "VALOR COMPRA USD"    HEADING "VALOR COMPRA USD"    FORMAT A18
COLUMN "VALOR COMPRA CLP"    HEADING "VALOR COMPRA CLP"    FORMAT A18
COLUMN "VALOR UNITARIO CLP"  HEADING "VALOR UNITARIO CLP"  FORMAT A18
COLUMN "STOCK"               HEADING "STOCK"               FORMAT 999G999
COLUMN "DESCUENTO CLP"       HEADING "DESCUENTO CLP"       FORMAT A18
COLUMN "PRECIO FINAL CLP"    HEADING "PRECIO FINAL CLP"    FORMAT A18
COLUMN "ALERTA"              HEADING "ALERTA"              FORMAT A24

ACCEPT TIPOCAMBIO_DOLAR PROMPT 'Ingresa tipo de cambio USD->CLP (p.ej. 950): ';
ACCEPT UMBRAL_BAJO      PROMPT 'Ingresa UMBRAL_BAJO de stock: ';
ACCEPT UMBRAL_ALTO      PROMPT 'Ingresa UMBRAL_ALTO de stock: ';

SELECT
  p.ID_PRODUCTO                                   AS "ID PRODUCTO",
  RPAD(p.DESCRIPCION,45)                          AS "DESCRIPCION",
  p.PROCEDENCIA                                   AS "ORIGEN",
  
  LPAD(NVL(TO_CHAR(p.VALOR_COMPRA_USD,'999G999G999D00'),'Sin registro'),18)
                                                  AS "VALOR COMPRA USD",
  LPAD(CASE
         WHEN p.VALOR_COMPRA_USD IS NULL THEN 'Sin registro'
         ELSE TO_CHAR(p.VALOR_COMPRA_USD * &TIPOCAMBIO_DOLAR,'999G999G999D00')
       END,18)                                     AS "VALOR COMPRA CLP",
  LPAD(TO_CHAR(p.VALOR_UNITARIO,'999G999G999D00'),18)
                                                  AS "VALOR UNITARIO CLP",
  NVL(p.TOTALSTOCK,0)                             AS "STOCK",
  LPAD(TO_CHAR(CASE WHEN p.TOTALSTOCK > 80
                    THEN p.VALOR_UNITARIO*0.10 ELSE 0 END,
            '999G999G999D00'),18)                 AS "DESCUENTO CLP",
  LPAD(TO_CHAR(CASE WHEN p.TOTALSTOCK > 80
                    THEN p.VALOR_UNITARIO*0.90 ELSE p.VALOR_UNITARIO END,
            '999G999G999D00'),18)                 AS "PRECIO FINAL CLP",
  CASE
    WHEN p.TOTALSTOCK IS NULL         THEN 'Sin datos'
    WHEN p.TOTALSTOCK <  &UMBRAL_BAJO THEN 'ALERTA: stock muy bajo'
    WHEN p.TOTALSTOCK <= &UMBRAL_ALTO THEN 'Reabastecer pronto'
    ELSE 'OK'
  END                                             AS "ALERTA"
FROM PRODUCTO p
WHERE LOWER(p.DESCRIPCION) LIKE '%zapato%'
  AND LOWER(p.PROCEDENCIA) = 'i'
ORDER BY p.ID_PRODUCTO DESC
;

--test rapido

SELECT 'CLIENTES'   AS TABLA, c.total AS TOTAL FROM (SELECT COUNT(*) AS total FROM CLIENTE)   c
UNION ALL
SELECT 'PRODUCTOS'  AS TABLA, p.total           FROM (SELECT COUNT(*) AS total FROM PRODUCTO)  p
UNION ALL
SELECT 'FACTURAS'   AS TABLA, f.total           FROM (SELECT COUNT(*) AS total FROM FACTURA)   f
UNION ALL
SELECT 'FORMA_PAGO' AS TABLA, fp.total          FROM (SELECT COUNT(*) AS total FROM FORMA_PAGO) fp;